export const SET_MAIN_DATA      = 'SET_MAIN_DATA'
export const SET_SIDEBAR        = 'SET_SIDEBAR'
export const CALLBACK_DATA      = 'CALLBACK_DATA'
export const DIALOG             = 'DIALOG'
export const AUTH_STATUS        = 'AUTH_STATUS'
export const SET_POST_DATA      = 'SET_POST_DATA'
