export const SET_MAIN_DATA      = 'SET_MAIN_DATA'
export const SET_SIDEBAR        = 'SET_SIDEBAR'
export const CALLBACK_DATA      = 'CALLBACK_DATA'
export const DIALOG             = 'DIALOG'
export const CALLBACK_ERROR     = 'CALLBACK_ERROR'
